### ISSUE TITLE
TypeError: cyclic object value

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-tabs-flow#25]
I'm getting `TypeError: cyclic object value` on the JavaScript console using Alpha 7, as simple as:

```java
@Route("tabs")
public class TabsTest extends Div {

    public TabsTest() {
        Tabs tabs = new Tabs();
        tabs.add(new Tab("Foo"));
        this.add(tabs);
    }
}
```

**Comment by heruan** [comment]
Tested with Flow Alpha 20: still an issue unfortunately.

**Comment by heruan** [comment]
Any update on this? Is this an actual `vaadin-tabs-flow` issue, or a Flow/`vaadin-tabs` one?

**Comment by ZheSun88** [comment]
I am trying to reproduce this error or something similar with `skeleton-starter-flow` with `10.0.0.alpha18` which is based on flow `1.0.0.alpha20` , but i cannot see the error. 

Could you provide me more information on this? @heruan

**Comment by heruan** [comment]
For example `jetty:run` https://github.com/heruan/flow-test and go to http://localhost:9998/tabs.

**Comment by ZheSun88** [comment]
I did `jetty:run` on the `master` branch of your repo, but i still cannot see any error.. My chrome version is  `63.0.3239.132`
![image](https://user-images.githubusercontent.com/31067185/36106737-d6a22fba-1020-11e8-9783-c33454fea00b.png)

**Comment by heruan** [comment]
Can you please try with Firefox? I see no error too with Chrome, but it happens in Firefox (and @Artur- reported it on Edge).

**Comment by ZheSun88** [comment]
aha, okay, i saw it now. thanks

**Comment by caalador** [comment]
The problem is in the `JSON.stringify(payloadJson)` used in the XhrConnection to build the XMLHttpRequest.

The problem payload is a rpc array making a`mSync` for `items` where the items array contains multiple `vaadin-tab` elements from which we get cyclic exceptions as FireFox parses also `__shady`, `__CE_state` etc that should not be parsed for the object. 

The breaking ones seem to be in the list 
```
key === "__shady" || key === "parent" || key === "__styleInfo" || key === "__CE_shadowRoot" || key === "host"
```
But there is also other information that is not needed for the request.
I'll continue looking into this.
