### ISSUE TITLE
Synch Tab#isSelected state from client side

### ISSUE THREAD

**Issue by cdir** [vaadin/vaadin-tabs-flow#51]
I was quite surprised when I finally found the little piece of information in the java doc of Tab#isSelected that this state is not synced from client side. May be I still miss some basic concepts of vaadin 10. But in my opinion it is very dangerous to have such API which gives just the wrong value. Additionally there is no hint where to get the correct value from. It seems like Tabs#getSelectedTab has the correct state. That means the state is already on server side.

If there is realy a good reason why this method should return the wrong value I wish the method name makes it clear. e.g. isServerSideSelected ;)

**Comment by pekam** [comment]
It's indeed quite weird API to have. I'm labeling this as a bug since it's so un-expected behavior, even though it technically does exactly what the javadoc says.

**Reason for this issue:**
The web components `selected` property doesn't have `notify: true`, which is because it's supposed to be used inside a `<vaadin-tabs>` component which handles the selection, and the `<vaadin-tab>` component itself doesn't have any logic for changing the property.
The Flow code generator creates getters for the properties, but it synchronizes the values from the client only if the component notifies the property changes with `propertyname-changed` events (in this case `selected-changed`). Those are fired only when `notify=true` for the property.

**Possible solution:**
Override the generated `isSelected()` method to ask the selected tab from the parent `Tabs` component and check if it equals this `Tab`.

**Comment by cdir** [comment]
@denis-anisimov looks good to me except I miss the part where you fix the javaDoc of Tab#isSelected(). If I did not overlook something in your PR there it still says:
```
     This property is not synchronized automatically from the client side, so
     the returned value may not be the same as in client side.
```

**Comment by denis-anisimov** [comment]
Good catch.
But the javadoc is still correct.
The property is not synchronized.
There is no any single change in the `Tab`  component itself.
The change is in the `Tabs`  component which updates the "selected" property from the server side.
And I'm not sure what to add into javadocs in that regard.
Any suggestions ?

**Comment by cdir** [comment]
@denis-anisimov the first part might be technically correct but I hope the second part `so the returned value may not be the same as in client side` not. I would prefere to simply remove these lines. As a developer using vaadni I do not care wether it is directly synced or synced via Tabs. And I thought that the state in Tabs is synced with the client, isn't it?

**Comment by pekam** [comment]
It's still possible to use a `Tab` without `Tabs`, even though it might not make any sense. So we have to document that behavior too.

Maybe:
`
If this component is not used inside a {@link Tabs} component, this property is not synchronized automatically from the client side.
`

**Comment by denis-anisimov** [comment]
The property is never synchronized automatically.
I would strongly recommend to avoid consider the fix as a way of synchronization.
The client side value may be still different just because it's possible to set it on the client side to any value from any place and since there is no synchronization it will be different.
The value on the server side doesn't reflect the client side property.
It's set on the server side from `Tabs` component.
Only this fact should be said on the javadocs.
