### ISSUE TITLE
IllegalArgumentException when switching tabs

### ISSUE THREAD

**Issue by razor5586** [vaadin/vaadin-tabs-flow#67]
Defining Tabs in a template and wiring them to Java by @Id causes an IllegalArgumentException when switching tabs in the browser. The issue occurs in version 1.03. Worked fine with version 1.02.

` java.lang.IllegalArgumentException: The 'index' argument should not be greater than or equals to the number of children components. It was: 1
`

**Comment by denis-anisimov** [comment]
This issue is a consequence of wrong assumptions made for implementation of 
`Tabs::getSelectedTab` and `Tabs::setSelectedTab` methods.

The current implementation assumes that all `Tab`s have been added via Java API so they are direct children of a `Tabs` component.

This is not true if `Tabs` has been injected via `@Id`.
The methods calculates the tab index based on the `Tab` component position in `Tabs` .
But this index is wrong if a `Tabs` structure  is defined on the client side.

E.g. I could have this template :

```
<template>
    <vaadin-tabs id="tabs">
	  <vaadin-tab id="tab1">Page 1</vaadin-tab>
          <slot></slot>
	  <vaadin-tab id="tab2">Page 2</vaadin-tab>
	</vaadin-tabs>
  </template>
```

Then there are a number of issues:
- I can have `tab1` injected via `@Id`. And I can use its instance in method `setSelectedTab`.  The method is broken since there is no any index for `tab1`: it's not a child of a `Tabs` component at all.
- I can add a number of `Tab` components into `Tabs` via `<slot>`.  Then both `getSelectedTab` , `setSelectedTab` method works incorrectly since the index on the client side is not equal index on the server side.

So all `Tab` related API methods in `Tabs` are completely broken in regard to injected `Tabs`.

This is a complicated issue.

**Comment by pleku** [comment]
Unfortunately we've concluded that there is no sensible way we can support this for now, thus this issue will be a known limitation with `Tabs`. It will not work as `@Id` mapped component when the child `vaadin-tab`s are created in the template file, so you should not try to mix client & server logic and content for the `Tabs` component.

As a workaround, you could try to use your own component for `@Id` mapping tabs like:
```java
@HtmlImport("...")
@Tag("vaadin-tabs")
public IdMappedTabs extends Component {

    public IdMappedTabs() {
    }

   public Registration addSelectionListener(PropertyChangeListener listener) {
       return getElement().addPropertyChangeListener("selected", listener);
   }

    public void setSelectedTabIndex(int index) {
        getElement().setProperty("selected", index);
    }

}
```
Additionally, if you set the initially selected tab from the template, then you'll not be able to know until after a roundtrip.

**Comment by martinisraelsen** [comment]
Would it be possible to note this on the Documentation pages for tabs? I think that other teams will run into this issue as well. May even consider writing a log warning if the tabs knows that they are @id referenced.

**Comment by pleku** [comment]
@martinisraelsen that is a good idea, https://github.com/vaadin/vaadin-tabs-flow/issues/94
