### ISSUE TITLE
Possibility to turn off first tab auto selection

### ISSUE THREAD

**Issue by letsdense** [vaadin/vaadin-tabs-flow#76]
Currently the first tab is auto selected after it's added to Tabs.

https://github.com/vaadin/vaadin-tabs-flow/blob/master/src/main/java/com/vaadin/flow/component/tabs/Tabs.java#L103

I would like to select the tab needed myself and not to do intermediate selection of 0-tab, which can cause an execution of a tab selection listener

**Comment by alexberazouski** [comment]
Just noticed that in 1.0.0 there was no that default first tab selection. May be better to get rid of it?

**Comment by alexberazouski** [comment]
In order not to break the existing behavior, what about introducing an option `doNotSelectFirstTabByDefault`? Current implementation makes us to have big workarounds

**Comment by pekam** [comment]
@pleku can we have a PO comment on this?

In summary:
- In `Tabs`, the first tab is automatically selected when it's added
- This fires a server-side selection-change-event
  - IMO this is correct, as selection changes from none to the first tab
- If you don't want the first tab selected, it's hard to work around this, since the selection event is fired for the first tab even if you change the selection immediately after adding the tabs
- Turning off this auto-selection now would be a breaking change
- To be backwards compatible, we could introduce a new ctor with a boolean flag: `Tabs(boolean autoSelectFirstTab)` or something ugly like that

**Comment by pleku** [comment]
If there are no tabs and a tab is added, the added tab should be selected and selection event should be fired immediately on the server side. This is how it works also in previous Framework versions. The fact that is didn't work like this in `1.0.0.` is a bug, and even though the fix was a behavior change, we the fix was taken in. It should have worked like this always, but this was not noticed before.

If I understand correctly, the issue @alexberazouski is with having some selection related logic for navigation ?
>Assume you load the page which corresponds 2nd tab. So after tabs initialized the first tab is selected; selection change event happens, and navigation to first page happens.

And this can be avoided with the flag returned by `isFromClient()` ?

For using the tabs for navigation you also need to consider that the 2nd tab might not be selected after all in the end, if there is some error during the routing, it might be that none of the tabs are actually selected. Thus, if you want to use tabs for showing the opened view, you should register an `AfterNavigationObserver` that updates the selected tab in the end.

**Comment by alexberazouski** [comment]
Exactly, the case is when vaadin-tabs are used as application menu.
I see nothing bad in case when no tabs are selected. For example, 404, 403 pages.

as for `isFromClient` flag: if we allow only client side selection, we disallow user to select tabs from server side, and user will need to make workarounds for it.

**Comment by pleku** [comment]
>Exactly, the case is when vaadin-tabs are used as application menu.
I see nothing bad in case when no tabs are selected. For example, 404, 403 pages.
>as for isFromClient flag: if we allow only client side selection, we disallow user to select tabs from server side, and user will need to make workarounds for it.

So how do you now unselect the tab when the 404 page is shown ? If not in an `AfterNavigatioObserver` ?

But I guess the real issue you're having is: for using the `Tabs` properly as a navigation menu component, the `Tab`s should have `RouterLink`s inside and you just update the highlighted tab in the `AfterNavigationObserver` .

But instead (it seems) you're using the server side selection event for triggering the navigation. And with 
>user will need to make workarounds for it
you mean with user the application developer. You basically need to have special handling for the first event that is fired from server side, not for all of them to "support server side tabs selection". I accept those workarounds as a better compromise to have instead of having the component working weirdly for other (more frequent) use cases. 

One enhancement might maybe be to have support for another property in the selection event, which states whether or not it is the initial event... Or mayhaps make it possible with API to add multiple tabs at once, where you specify the selected tab separately.

**Comment by alexberazouski** [comment]
Menu items could be not only links, but also could trigger some action.
If the first tab is action menu item, it will be triggered everytime the page is opened.

As a workaround we should ignore not only the very first selection, but also check if Tabs ever have been cleared, and then ignore first selection again.

In my case I do not know which tab should be selected, when I populate the menu.

About enhancement: yes, such event property could solve my problem

**Comment by pleku** [comment]
To summarize: the API we could add is
- `setAutoselect(boolean autoselect)` & `boolean IsAutoselect()` with default `true` and would control
  - the selection of the first tab added
  - the selection of the _next_ tab when a tab is removed
  - this would mean that on tab removal should still fire a `SelectedChangedEvent`, but there the selection goes from a tab to nothing selected
- add data to the `SelectedChangedEvent`
  - `Tab getSelectedTab()`
  - `Tab getOldSelectedTab()` 
  - `boolean isInitialSelection()` this on is `true` only when the first tab was selected automatically when `autoselect = true`
